### ISSUE TITLE
panic: runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by navneetv** [dpetzold/kube-top#1]
Compiles ok but get a panic with the stack details while executing. 

goroutine 1 [running]:
github.com/dpetzold/kube-top/pkg/ui.updateContainers(0xc4200a2000)
        /root/go/src/github.com/dpetzold/kube-top/pkg/ui/containers.go:88 +0x820
github.com/dpetzold/kube-top/pkg/ui.UpdatePanels()
        /root/go/src/github.com/dpetzold/kube-top/pkg/ui/ui.go:78 +0x41
github.com/dpetzold/kube-top/pkg/ui.showWindow(0x123e0c0)
        /root/go/src/github.com/dpetzold/kube-top/pkg/ui/ui.go:105 +0x30
github.com/dpetzold/kube-top/pkg/ui.KubeTop(0xc4204d67c0, 0x11c9ff0, 0x7)
        /root/go/src/github.com/dpetzold/kube-top/pkg/ui/ui.go:186 +0x192
main.main()
        /root/go/src/github.com/dpetzold/kube-top/cmd/kube-top/main.go:59 +0x44d

**Comment by dpetzold** [comment]
Hey @navneetv. Thank you for trying kube-top out. I think I fixed the issue with this commit:

https://github.com/dpetzold/kube-top/commit/497b60a03205dd9e72d1b975889ae649a5d0ad47

Can you try building and running it again.

**Comment by navneetv** [comment]
Solution worked.
